#!/usr/bin/env node
// Builds the Rust crates to WebAssembly and embeds the binaries as base64 JavaScript modules in src/.
// Requires a Rust toolchain with the wasm32-unknown-unknown target (`rustup target add wasm32-unknown-unknown`).
// Usage: node wasm/build.mjs [--debug]
import {execSync} from "child_process";
import {readFileSync, writeFileSync, statSync} from "fs";
import {dirname, join} from "path";
import {fileURLToPath} from "url";

const wasmDir = dirname(fileURLToPath(import.meta.url));
const debug = process.argv.includes("--debug");
const crates = [
    {package: "xeokit-las", profile: "release", file: "xeokit_las.wasm", out: "../src/plugins/LASLoaderPlugin/lasWasm.js", name: "lasWasm"},
    {package: "xeokit-gltf", profile: "release-small", file: "xeokit_gltf.wasm", out: "../src/plugins/GLTFLoaderPlugin/gltfWasm.js", name: "gltfWasm"}
];
for (const crate of crates) {
    const profile = debug ? "debug" : crate.profile;
    execSync(`cargo build --target wasm32-unknown-unknown -p ${crate.package} --profile ${debug ? "dev" : crate.profile}`, {cwd: wasmDir, stdio: "inherit"});
    const path = join(wasmDir, "target/wasm32-unknown-unknown", profile, crate.file);
    let bytes = readFileSync(path);
    try { // Optional: shrink with binaryen's wasm-opt when it is installed
        execSync(`wasm-opt -O3 --strip-debug -o "${path}.opt" "${path}"`, {stdio: "ignore"});
        bytes = readFileSync(`${path}.opt`);
    } catch (e) {
    }
    const base64 = bytes.toString("base64");
    const js = `/* eslint-disable */\n// Generated by wasm/build.mjs from wasm/${crate.file.replace("xeokit_", "").replace(".wasm", "")} - do not edit.\n// ${crate.file}: ${bytes.length} bytes\n/** @private */\nexport const ${crate.name} = "${base64}";\n`;
    writeFileSync(join(wasmDir, crate.out), js);
    console.log(`${crate.out}: ${bytes.length} bytes of wasm, ${statSync(join(wasmDir, crate.out)).size} bytes of JS`);
}
